name: Haskell Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GHC
      run: |
        sudo apt-get update
        sudo apt-get install -y ghc

    - name: Build project
      run: |
        ghc -o todo todoList.hs
        # Asegúrate de ajustar el comando según la estructura de tu proyecto y el nombre del archivo

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: todo-artifact
        path: ./todo

    - name: Test project
      run: |
        # Agrega comandos para ejecutar pruebas, si es aplicable
