name: Haskell Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.7'

    - name: Build project
      run: |
        ghc -o todo todoList.hs
        # Asegúrate de ajustar el comando según la estructura de tu proyecto y el nombre del archivo

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: todo-artifact
        path: ./todo

    - name: Test project
      run: |
        # Agrega comandos para ejecutar pruebas, si es aplicable
